ControleFinanceiro/Controllers/EmpresaController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VO;

namespace ControleFinanceiro.Controllers
{
    public class EmpresaController : Controller
    {
        private void MontarTitulo(int tipo)
        {
            switch (tipo)
            {
                case 1:
                    ViewBag.titulo = "Cadastrar Empresa";
                    ViewBag.subtitulo = "Cadastre aqui suas empresas";
                    break;
                case 2:
                    ViewBag.titulo = "Alterar Empresa";
                    ViewBag.subtitulo = "Altere aqui suas empresas";
                    break;
                case 3:
                    ViewBag.titulo = "Consultar Empresa";
                    ViewBag.subtitulo = "Consulte aqui suas empresas";
                    break;
            }
        }

        // GET: Empresa
        public ActionResult Cadastrar()
        {
            MontarTitulo(1);
            return View();
        }
        public ActionResult Alterar(int? cod_empresa)
        {
            if(cod_empresa == null || cod_empresa == 0)
            {
                CarregarEmpresa();
                MontarTitulo(3);
                return View("Consultar");
            }

            EmpresaDAO dao = new EmpresaDAO();
            EmpresaVO vo = dao.DetalheEmpresa(Convert.ToInt32(cod_empresa), 1);

            ViewBag.cod_empresa = vo.CodigoEmpresa;
            ViewBag.nome_empresa = vo.NomeEmpresa;
            ViewBag.endereco_empresa = vo.EnderecoEmpresa;
            ViewBag.telefone_empresa = vo.TelefoneEmpresa;
            MontarTitulo(2);
            return View();
        }
        public ActionResult Consultar()
        {
            CarregarEmpresa();
            MontarTitulo(3);
            return View();
        }
        public ActionResult Gravar(int? cod_empresa, string nome_empresa, string endereco_empresa, string telefone_empresa)
        {
            if(nome_empresa.Trim() == "" || endereco_empresa.Trim() == "" || telefone_empresa.Trim() == "")
            {
                ViewBag.ret = 0;
            }
            else
            {
                EmpresaVO vo = new EmpresaVO();
                EmpresaDAO dao = new EmpresaDAO();

                vo.CodigoEmpresa = cod_empresa == null ? 0 : Convert.ToInt32(cod_empresa);
                vo.CodigoUsuario = 1;
                vo.EnderecoEmpresa = endereco_empresa;
                vo.NomeEmpresa = nome_empresa;
                vo.TelefoneEmpresa = telefone_empresa;

                if(cod_empresa != null)
                {
                    ViewBag.ret = dao.AlterarEmpresa(vo);

                    ViewBag.cod_empresa = cod_empresa;
                    ViewBag.nome_empresa = nome_empresa;
                    ViewBag.telefone_empresa = telefone_empresa;
                    ViewBag.endereco_empresa = endereco_empresa;
                }
                else
                {
                    ViewBag.ret = dao.InserirEmpresa(vo);
                }


                ViewBag.ret = dao.InserirEmpresa(vo);
            }

            MontarTitulo(cod_empresa == null ? 1 : 2);
            return View(cod_empresa == null ? "Cadastrar" : "Alterar");
        }

        private void CarregarEmpresa()
        {
            EmpresaDAO dao = new EmpresaDAO();
            ViewBag.ListaEmpresa = dao.ConsultarEmpresa(1);
        }
    }

}

ControleFinanceiro/Views/Empresa/Alterar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

@using (Html.BeginForm("Gravar", "Empresa", FormMethod.Post))
{
    <input type="hidden" name="cod_empresa" value="@ViewBag.cod_empresa" />
    <div class="form-group">
        <label>Nome da Empresa</label>
        <input class="form-control" placeholder="Digite aqui..." name="nome_empresa" value="@ViewBag.nome_empresa"/>
    </div>
    <div class="form-group">
        <label>Endereço</label>
        <input class="form-control" placeholder="Digite aqui..." name="endereco_empresa" value="@ViewBag.endereco_empresa" />
    </div>
    <div class="form-group">
        <label>Telefone</label>
        <input class="form-control" placeholder="Digite aqui..." name="telefone_empresa" value="@ViewBag.telefone_empresa" />
    </div>
    <button type="submit" class="btn btn-success">Salvar</button>
}

ControleFinanceiro/Views/Empresa/Cadastrar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

@using (Html.BeginForm("Gravar", "Empresa", FormMethod.Post))
{
    <div class="form-group">
        <label>Nome da Empresa</label>
        <input class="form-control" placeholder="Digite aqui..." name="nome_empresa" />
    </div>
    <div class="form-group">
        <label>Endereço</label>
        <input class="form-control" placeholder="Digite aqui..." name="endereco_empresa" />
    </div>
    <div class="form-group">
        <label>Telefone</label>
        <input class="form-control" placeholder="Digite aqui..." name="telefone_empresa" />
    </div>
    <button type="submit" class="btn btn-success">Salvar</button>
}

ControleFinanceiro/Views/Empresa/Consultar.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<!-- /. ROW  -->
<hr />

<div class="row">
    <div class="col-md-12">
        <!-- Advanced Tables -->
        <div class="panel panel-default">
            <div class="panel-heading">
                Empresas Cadastradas
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Nome da Empresa</th>
                                <th>Endereço</th>
                                <th>Telefone</th>
                                <th>Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var item in ViewBag.ListaEmpresa)
                                {
                                    <tr class="odd gradeX">
                                        <td>@item.NomeEmpresa</td>
                                        <td>@item.EnderecoEmpresa</td>
                                        <td>@item.TelefoneEmpresa</td>
                                        <td>
                                            <a href="/Empresa/Alterar?cod_empresa=@item.CodigoEmpresa" class="btn btn-block btn-warning btn-xs">Alterar</a>
                                        </td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!--End Advanced Tables -->
    </div>
</div>
<!-- /. ROW  -->