ControleFinanceiro/Controllers/MovimentoController.cs
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VO;

namespace ControleFinanceiro.Controllers
{
    public class MovimentoController : Controller
    {
        private void MontarTitulo(int tipo)
        {
            switch (tipo)
            {
                case 1:
                    ViewBag.titulo = "Realizar Movimento";
                    ViewBag.subtitulo = "Realize aqui o movimento";
                    break;
                case 2:
                    ViewBag.titulo = "Alterar Movimento";
                    ViewBag.subtitulo = "Realize aqui alteração dos movimentos";
                    break;
                case 3:
                    ViewBag.titulo = "Consultar Movimento";
                    ViewBag.subtitulo = "Realize aqui consulta dos movimentos";
                    break;
            }
        }
        // GET: Movimento
        public ActionResult ConsultarMovimento()
        {
            MontarTitulo(3);
            return View();
        }

        public ActionResult RealizarMovimento()
        {
            MontarTitulo(1);
            CarregarCombos();
            return View();
        }

        public ActionResult AlterarMovimento(int? cod)
        {
            if (cod == null || cod == 0)
            {
                MontarTitulo(3);
                return View("ConsultarMovimento");
            }

            MontarTitulo(2);
            return View();
        }

        public ActionResult Gravar(int? cod, string categoria_movimento, string data_movimento, string valor_movimento, string tipo_movimento, string empresa_movimento, string obs_movimento)
        {
            if (tipo_movimento == "" || categoria_movimento == "" || empresa_movimento == "" || data_movimento == "")
            {
                ViewBag.ret = 0;
            }
            else
            {
                MovimentoDAO dao = new MovimentoDAO();
                MovimentoVO vo = new MovimentoVO();

                vo.TipoMovimento = Convert.ToInt32(tipo_movimento); 
                vo.DataMovimento = Convert.ToDateTime(data_movimento); 
                vo.ValorMovimento = Convert.ToDecimal(valor_movimento); 
                vo.ObsMovimento = obs_movimento; 
                vo.CodigoEmpresa = Convert.ToInt32(empresa_movimento); 
                vo.CodigoCategoria = Convert.ToInt32(categoria_movimento); 
                vo.CodigoMovimento = (cod == null ? 0 : Convert.ToInt32(cod));
                vo.CodigoUsuario = 1;

                
                if(cod == null)
                {
                    ViewBag.ret = dao.RealizarMovimento(vo);
                }
                else
                {
                    ViewBag.ret = dao.AlterarMovimento(vo);

                    ViewBag.Tipo = tipo_movimento;
                    ViewBag.Data = data_movimento;
                    ViewBag.Valor = valor_movimento;
                    ViewBag.Empresa = empresa_movimento;
                    ViewBag.Obs = obs_movimento;
                    ViewBag.Categoria = categoria_movimento;
                    ViewBag.Codigo = cod;
                }
            }
            CarregarCombos();
            MontarTitulo(cod == null ? 1 : 2);
            return View(cod == null ? "RealizarMovimento" : "AlterarMovimento");
        }
        public ActionResult PesquisarMovimento(string data_inicial, string data_final, string tipo_movimento)
        {
            if(data_final == "" || data_inicial == "")
            {
                ViewBag.ret = 0;
            }
            else
            {
                MovimentoDAO dao = new MovimentoDAO();

                List<MovimentoVO> lst = dao.ConsultarMovimento(1, Convert.ToInt32(tipo_movimento), Convert.ToDateTime(data_inicial), Convert.ToDateTime(data_final));

                ViewBag.ListaMovimento = lst;
            }
            MontarTitulo(3);
            return View("ConsultarMovimento");
        }
        private void CarregarCategoria()
        {
            CategoriaDAO dao = new CategoriaDAO();
            List<CategoriaVO> lst = dao.ConsultarCategoria(1);
            ViewBag.ListaCategoria = lst;
        }
        private void CarregarEmpresa()
        {
            EmpresaDAO dao = new EmpresaDAO();
            List<EmpresaVO> lst = dao.ConsultarEmpresa(1);
            ViewBag.ListaEmpresa = lst;
        }
        private void CarregarCombos()
        {
            CarregarCategoria();
            CarregarEmpresa();
        }
    }
}

ControleFinanceiro/Views/Movimento/AlterarMovimento.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("Gravar", "Movimento", FormMethod.Post))
{
    <input type="hidden" name="cod" value=""/>
    <div class="form-group">
        <label>Categoria</label>
        <select class="form-control" name="categoria_movimento">
            <option value="">Selecione</option>
            <option value="1">Entrada</option>
            <option value="2">Saida</option>
        </select>
    </div>
    <div class="form-group">
        <label>Data Movimento</label>
        <input type="date" class="form-control" placeholder="Digite aqui..." name="data_movimento" />
    </div>
    <div class="form-group">
        <label>Valor Movimento</label>
        <input class="form-control" placeholder="Digite aqui..." name="valor_movimento" />
    </div>
    <div class="form-group">
        <label>Tipo do Movimento</label>
        <select class="form-control" name="tipo_movimento">
            <option value="">Selecione</option>
            <option value="1">Entrada</option>
            <option value="2">Saida</option>
        </select>
    </div>
    <div class="form-group">
        <label>Empresa</label>
        <select class="form-control" name="empresa_movimento">
            <option value="">Selecione</option>
            <option value="1">Entrada</option>
            <option value="2">Saida</option>
        </select>
    </div>

    <div class="form-group">
        <label>Observação</label>
        <textarea class="form-control" placeholder="Digite aqui..." name="obs_movimento"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Salvar</button>
}

ControleFinanceiro/Views/Movimento/ConsultarMovimento.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
@using (Html.BeginForm("PesquisarMovimento", "Movimento", FormMethod.Post))
{
    <div class="form-group">
        <label>Tipo do Movimento</label>
        <select class="form-control" name="tipo_movimento">
            <option value="">Todos</option>
            <option value="1">Entrada</option>
            <option value="2">Saida</option>
        </select>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label>Data Inicial</label>
            <input type="date" class="form-control" placeholder="Digite aqui..." name="data_inicial" />
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label>Data Final</label>
            <input type="date" class="form-control" placeholder="Digite aqui..." name="data_final" />
        </div>
    </div>
    <center>
        <button type="submit" class="btn btn-info">Procurar</button>
    </center>
}
<hr />
@{
    if (ViewBag.ListaMovimento != null)
    {
        if (ViewBag.ListaMovimento.Count > 0)
        {
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Movimentos Encontrados
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>Data</th>
                                            <th>Nome da Empresa</th>
                                            <th>Categoria</th>
                                            <th>Tipo</th>
                                            <th>Valor</th>
                                            <th>Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{
                                            foreach (var item in ViewBag.ListaMovimento)
                                            {
                                                <tr class="odd gradeX">
                                                    <td>@item.DataMovimento</td>
                                                    <td>@item.Empresa</td>
                                                    <td>@item.Categoria</td>
                                                    <td>@item.NomeTipo</td>
                                                    <td>R$ @item.ValorMovimento</td>
                                                    <td>
                                                        <a class="btn btn-block btn-warning btn-xs" href="/Movimento/AlterarMovimento?cod=@item.CodigoMovimento">Alterar</a>
                                                    </td>
                                                </tr>
                                            }
                                        }


                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                    <!--End Advanced Tables -->
                </div>
            </div>
            <!-- /. ROW  -->
        }
        else
        {
            <div class="alert alert-info">
                Não existem dados para serem exibidos!
            </div>
        }

    }

}

ControleFinanceiro/Views/Movimento/RealizarMovimento.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

@using (Html.BeginForm("Gravar", "Movimento", FormMethod.Post))
{
    <div class="form-group">
        <label>Tipo do Movimento</label>
        <select class="form-control" name="tipo_movimento">
            <option value="">Selecione</option>
            <option value="1">Entrada</option>
            <option value="2">Saida</option>
        </select>
    </div>
    <div class="form-group">
        <label>Data Movimento</label>
        <input type="date" class="form-control" placeholder="Digite aqui..." name="data_movimento" />
    </div>
    <div class="form-group">
        <label>Valor Movimento</label>
        <input class="form-control" placeholder="Digite aqui..." name="valor_movimento" />
    </div>
    <div class="form-group">
        <label>Empresa</label>
        <select class="form-control" name="empresa_movimento">
            <option value="">Selecione</option>
            @{
                foreach (var item in ViewBag.ListaEmpresa)
                {
                    <option value="@item.CodigoEmpresa">@item.NomeEmpresa</option>
                }
            }
        </select>
    </div>
    <div class="form-group">
        <label>Categoria</label>
        <select class="form-control" name="categoria_movimento">
            <option value="">Selecione</option>
            @{
                foreach (var item in ViewBag.ListaCategoria)
                {
                    <option value="@item.Codigo">@item.NomeCategoria</option>
                }
            }
        </select>
    </div>
    <div class="form-group">
        <label>Observação</label>
        <textarea class="form-control" placeholder="Digite aqui..." name="obs_movimento"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Salvar</button>
}